[tool.usort]

first_party_detection = false

[tool.black]

line-length = 120
target-version = ["py37"]

[build-system]
requires = [
    "setuptools",
    "wheel",
    "ninja",
    "cmake",
    "torch",
]
