# Copyright (c) Facebook, Inc. and its affiliates.
 
 
from typing import List, Tuple


# TODO: Add pyi generate script
class S3Handler():
    def __init__(self, request_timeout_ms: int, region: str) -> None: ...
    def s3_read(self, url: str) -> bytes: ...
    def list_files(self, prefix: str)  -> List[str]: ...
    def set_buffer_size(self, buffer_size: int) -> None: ...
    def set_multi_part_download(self, multi_part_download: bool) -> None: ...
    def clear_marker(self) -> None: ...
