

# This script sets up an Ec2 instance with elastic IP and a disk volume
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: c5n.large
    AllowedValues:
      - c5n.large
      - p2.2xlarge
      - p3.2xlarge
      - p3.8xlarge
    Description: Instance type CPU, GPU
  DiskSize:
    Type: Number
    Default: 100
    Description: Disk size in GB
  DiskType:
    Type: String
    Default: gp2
    AllowedValues:
      - gp2
      - gp3
      - io1
      - io2
      - sc1
      - st1
      - standard
    Description: Enter Disk type SSD, HDD

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0306d46d05aaf8663 # Deep Learning AMI
      InstanceType: 
        Ref: InstanceTypeParameter
      SecurityGroups:
        - !Ref SSHSecurityGroup

  # Elastic IP so I can easily ssh into the machine
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyInstance

  # Open security group for SSH
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22


  NewVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 
        Ref: DiskSize
      VolumeType:
        Ref: DiskType
      AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
      Tags:
        - Key: MyTag
          Value: TagValue
    DeletionPolicy: Snapshot

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref MyInstance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh
